"""empty message

Revision ID: cb7d3633e6e0
Revises: 
Create Date: 2022-12-16 11:53:21.424722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7d3633e6e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PhoneNumbers',
    sa.Column('phone_num_id', sa.Integer(), nullable=False),
    sa.Column('phone_num', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('phone_num_id')
    )
    op.create_table('Profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('total_searched_cars', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('phone_num_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone_num_id'], ['PhoneNumbers.phone_num_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['Profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Profiles')
    op.drop_table('PhoneNumbers')
    # ### end Alembic commands ###
